My Capstone Project(Durban July Fashion Show)
Munyabelden/Munyabelden.github.io pull request #1
Opened 2023-02-16 09:23 UTC by Munyabelden

-Created using html css and javascript
-Added  github flow  for the linters
Added readme file and Mit license

2023-02-16 11:10 UTC, Reem-lab requested changes
# Hi @Munyabelden, 👋🏻👋🏻 

Great job so far! 💯🔥♻
There are some issues that you still need to work on to go to the next project but you are almost there!
### Your design is awesome, I like it 💯🤩💪🏻✨🚀🚀⭐
<img src="https://media3.giphy.com/media/SDunHzTgSZbSuQy1EP/giphy.gif"/>

## Highlights
- No Linters erros 💯
- Followed GitHub flow ✅
- Great working on the fuctionality in the JS file✅
- Descriptive PR 💯
- Professional README ⭐🔥🔥🔥✅✅
- Great working on the design 🔥🔥


## Required Changes ♻️
_Check the comments under the review._

- [ ] I could see that you forget to record a video for the presentation so please recored a video and don't forget to  highlight some interesting piece of code or something you built that you are very proud of.as written in the requirements 🙏🏻♻💯🤩👏🏻👏🏻

![image](https://user-images.githubusercontent.com/58553711/218937493-165b6ccc-2161-4860-8273-e1527f58d587.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +      <span>@Galleria Mall, Durban SA</span>
- [ ] I think it would be great if you add more font size and font weight to this span to make it identical to the original design since it is one of the requirements 🔥🚀💯


- Your design
![image](https://user-images.githubusercontent.com/58553711/219337156-4f8160f1-c78f-4342-8065-cbbbd4580cf0.png)

- Given
![image](https://user-images.githubusercontent.com/58553711/219337259-eb3a064d-b8d0-486b-9327-5fd74fabd80e.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +    </footer>
- [ ] Great job for adding the functionality for the cards but I think you should still remove the footer in Home page for the mobile version since it is not found in the given design so please just remove it from Home page in mobile version 💯🚀♻⭐✨✨✨

- Your design
![image](https://user-images.githubusercontent.com/58553711/219337811-10595bc7-a31a-49f7-bb1f-aaa5948931d4.png)


- Given design
![image](https://user-images.githubusercontent.com/58553711/219302804-98859ed6-29be-4710-9eae-b0b16843c389.png)

2023-02-16 11:10 UTC, Reem-lab commented on about.html
> +        </footer>
- [ ] I think it would be great if you align the footer items beside each others the heading and the text so please style it by using flex for example so kindly update it to match the original design 💯🚀🔥😊


- Your design
![image](https://user-images.githubusercontent.com/58553711/219338576-66fc06f5-a5fe-4c95-9543-58c79f6d01ed.png)

- Given
![image](https://user-images.githubusercontent.com/58553711/219338778-381e7c27-707c-4468-9064-433497c6e219.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +          </ul>
- [ ] Great job so far 👏🏻👏🏻 but I think it would be great if you add the listed items in the navbar even if they are not working for now like program, join, sponser and new so please add them to the navbar for now because they are important to match the original design and maybe later you can implement the extra pages in the future if you want 👏🏻😊🔥🚀💯

- your design
![image](https://user-images.githubusercontent.com/58553711/219339669-7bd384f9-b0cc-4f91-b443-2b9db7a44d79.png)

- Given design
![image](https://user-images.githubusercontent.com/58553711/219339806-a5eaa66a-706a-43d2-8e01-97a92fb5b1a5.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +            <h3>DJ Festival</h3>
- [ ] I think it would be nicer if you have your project own logo here since you are just putting it as heading but it is a logo in the Given page and I think that would be great addition to your page 🙏🏻💯🚀🤩🤩 You can make it with canvas it is also found in your dashboard GitHub Education so you can get it for free for a period 🤩🚀
### It would be great experince if you try it now because you are going to need it in the future 💯💯


- [ ] I think the logo should lead to the home page as well so if the user in about page and press on logo so it should lead to the home page so please link it with logo 💯⭐♻♻

![image](https://user-images.githubusercontent.com/58553711/219340929-b9c9c7af-c183-4f5b-b472-5efb1e772a58.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +        </div>
- [ ] I think it would be very nice to have some animation to your cards as shown in the given design so whenever the user press on the card so it make a border to the card like the given design and that's important to improve from user experience (UX) ♻⭐💯🚀🔥

- [ ] Great hob so far but I think it would be great if you add more height to the cards to match the original desgin as much as possible so please add more height to the cards here 🔥🙏🏻
- Your design
![image](https://user-images.githubusercontent.com/58553711/219341859-3c310abb-1be7-426d-902f-1a69591d0efb.png)

-Given 
![image](https://user-images.githubusercontent.com/58553711/219341778-278670b7-c342-450a-9d35-6e39a12c0785.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +        <a href="#" class="program-button">Join CC Global Summit 2015</a>
- [ ] Great job for adding the button here but as I can see it is different in desktop version in the given design but you forget to style it so please style it here to match the given design I will show you here 🙏🏻🔥🤩

- Your design
![image](https://user-images.githubusercontent.com/58553711/219342532-520b5acd-abd1-4b22-8119-d08787dcad6d.png)

- Given 
![image](https://user-images.githubusercontent.com/58553711/219342624-1ac76210-4790-4516-98fb-fc9f22ddf53f.png)

2023-02-16 11:10 UTC, Reem-lab commented on index.html
> +    </footer>
- [ ] Great job on the footer and partner section in home page for desktop version but I think it would be great if you add the item in the footer here beside each others so kindly style them with flex and more styles to match the original design 🤩🔥🙏🏻

- Your design

![image](https://user-images.githubusercontent.com/58553711/219343495-3a61e980-daff-4942-a0f4-c51f06d47798.png)


- Given design 
![image](https://user-images.githubusercontent.com/58553711/219343646-3f7a77f1-1be2-40a1-8d2b-689fd676828a.png)

2023-02-16 11:10 UTC, Reem-lab commented on readme.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ OPTINOAL ] Great hob for adding the appropriate credit to the author. Therefore you can add a ink to the design as well it would be great if you add it 🔥✨⭐💯🚀Like this ⬇⬇

Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author.

2023-02-16 11:10 UTC, Reem-lab commented on readme.md
> +- [Live Demo Link](https://munyabelden.github.io/)
- [ ] Since you made a huge efforts I coudn't see your link is broken so please deploy your project well to let it easy for the users to just see your project live so I highly recommend adding it according to the requirments 🤩💯♻🙏🏻

![image](https://user-images.githubusercontent.com/58553711/218936871-0f872bf5-7b37-4d58-a08a-257b4060c970.png)

2023-02-16 14:32 UTC, joskalenda commented on index.html
> +    </footer>
- [ ] This is a simple comment, I understand the time and energy you have taken on doing this as asked by @Reem-lab, but please revert the changes, it should be present eventually as said in the requirement,
<img width="369" alt="1" src="https://user-images.githubusercontent.com/77843050/219393177-ffb3486c-e664-41ad-838f-9f0b2f61b560.png">

2023-02-16 14:39 UTC, Munyabelden commented
Sorry I don't quite understand what you are saying kindly elaborate

On Thu, 16 Feb 2023, 16:32 Jos Kalenda, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Munyabelden/Munyabelden.github.io/pull/1#discussion_r1108554660>
> :
>
> > +    <footer class="home-footer">
> +      ***@***.*** Durban July South Africa <span>Some Rights Reserved</span></p>
> +    </footer>
>
>
>    - This is a simple comment, I understand the time and energy you have
>    taken on doing this as asked by @Reem-lab <https://github.com/Reem-lab>,
>    but please revert the changes, it should be present eventually as said in
>    the requirement,
>
> [image: 1]
> <https://user-images.githubusercontent.com/77843050/219393177-ffb3486c-e664-41ad-838f-9f0b2f61b560.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Munyabelden/Munyabelden.github.io/pull/1#discussion_r1108554660>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A32THZD6RFQAT7CJ6OB3TDLWXY3ADANCNFSM6AAAAAAU545HXY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-16 14:49 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Munyabelden , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media4.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/> |

### Highlights
✅ ... Green litners
✅ ... Great readme file
✅ .. Good design

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 14:49 UTC, joskalenda commented on index.html
> +    </div>
- [ ] This comment is marked as optional because the previous reviewer did not mention it before, but we all agree, you and me that this section I just highlighted are missing in your design, to make your app more better, I would recommend you work on these few touches ❤️ 
<img width="657" alt="1" src="https://user-images.githubusercontent.com/77843050/219396687-e1aa02a5-dd1d-4e0f-b3ff-f55465c6b0c5.png">

2023-02-16 14:53 UTC, merged

2023-02-18 23:41 UTC, Reem-lab commented on index.html
> +    </footer>
Hello @joskalenda I don't think so because in the design there is no footer and partner sectin in home page for the mobile version please check the design you will see  😊

2023-02-19 07:23 UTC, joskalenda commented
Okay❤

Best Regards

Jos

On Sun, Feb 19, 2023, 1:41 AM Reem janina ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/Munyabelden/Munyabelden.github.io/pull/1#discussion_r1111125511>
> :
>
> > +    <footer class="home-footer">
>
> +      ***@***.*** Durban July South Africa <span>Some Rights Reserved</span></p>
>
> +    </footer>
>
>
> Hello @joskalenda <https://github.com/joskalenda> I don't think so
> because in the design there is no footer and partner sectin in home page
> for the mobile version please check the design you will see 😊
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Munyabelden/Munyabelden.github.io/pull/1#discussion_r1111125511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASR4U2UZPQCFALLZD4E3RIDWYFM2FANCNFSM6AAAAAAU545HXY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>